---
- name: Install and Configure MSSQL on Windows hosts
  hosts: all
  tasks:
    - name: Including Windows MSSQL role
      include_role:
        name: win-mssql
      vars:
        ec2_lb_filters: 
          'tag:Name': "{{ ec2_scope }}"
          'instance-state-name': running
